### ISSUE TITLE
Files are checked as they are in the workspace rather than the index

### ISSUE THREAD

**Issue by nicholasbishop** [sebdah/git-pylint-commit-hook#26]
Example:
1. Edit foo.py in a way that introduces style errors
2. Run "git add foo.py"
3. Fix style errors in foo.py
4. Run "git commit"

The commit succeeds and commits foo.py with style errors because the linter ran on the workspace version of the file rather than the index.

**Comment by evanunderscore** [comment]
Didn't see anyone else working on this so I took a shot at it. I'm not a git expert but this solution seems pretty solid.
