### ISSUE TITLE
Hook brokes merging state

### ISSUE THREAD

**Issue by timocov** [sebdah/git-pylint-commit-hook#53]
If you run `git-pylint-commit-hook` when you are in merging (for example when you have conflicts) you will missed merging state.
Possible reason is using [stash](https://github.com/sebdah/git-pylint-commit-hook/blob/b2db938741c16c24791a4dc4ad4933714a91da5e/git_pylint_commit_hook/commit_hook.py#L137)

**Comment by evanunderscore** [comment]
I initially added the stash in order to fix #26, but I no longer think this is good default behavior. I haven't looked into this particular problem, but I think it would be a good idea to make the stashing opt-in regardless.

**Comment by sebdah** [comment]
A fix for this (#56) has been released in version 2.3.0.
