### ISSUE TITLE
pylint is invoked incorrectly if .pylintrc is not present

### ISSUE THREAD

**Issue by volviq** [sebdah/git-pylint-commit-hook#62]
When committing, the pylint result is always shown as "0" although the python files are getting a rating of "10.0" when pylint is run manually.
If no .pylintrc is present, the script should not pass a parameter for .pylintrc, so that pylint runs with defaults.

**Comment by volviq** [comment]
Alternatively, it would be good, if a global .pylintrc can be used.
The use case for this is having a hooksPath set in .gitconfig. There will always be project which do not yet have a .pylintrc inside the repository.

At least the error messages of pylint should be printed with some meaning. see https://github.com/sebdah/git-pylint-commit-hook/issues/58

**Comment by volviq** [comment]
Created https://github.com/sebdah/git-pylint-commit-hook/pull/63
Apparently I didn't link this correctly to this story - I'm happy to amend the commit or branch name.
what do I need to regard here?

**Comment by sebdah** [comment]
Fixed with #63 and released in 2.4.0
