### ISSUE TITLE
Should check "if ignored" and then check "if python file"

### ISSUE THREAD

**Issue by wlwg** [sebdah/git-pylint-commit-hook#68]
Currently in the logic of filtering files to run pylint against, it first checks if the file is python type and then checks if the file is ignored (
https://github.com/sebdah/git-pylint-commit-hook/blob/master/git_pylint_commit_hook/commit_hook.py#L226 )

It might be better to check "if ignored" first and then check "if python file".  It makes sense in that there's no need of checking "if it's python file" if the file is ignored.  Also it could sometimes avoid some pain as reported in #67.

**Comment by sebdah** [comment]
Resolved in 2.5.1.
